[tool.poetry]
name = "libanaf"
version = "0.1.0"
description = "ANAF API Authentication Command Line Application"
authors = ["Catalin Trifu <ctrifu@gmail.com>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
rauth = "^0.7.3"
typer = "^0.12.3"
rich = "^13.7.1"
python-dotenv = "^1.0.1"
envtoml = "^0.1.2"
requests-oauthlib = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
